version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "5379:6379"
  scoring:
    image: scoring:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STORAGE_HOST=redis
      - STORAGE_PORT=6379
    depends_on:
      - redis
